//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackList.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", ConfigurationName="ServiceReference.OperatorRequestPortType")]
    public interface OperatorRequestPortType {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://vigruzki.rkn.gov.ru/OperatorRequest/).
        [System.ServiceModel.OperationContractAttribute(Action="http://vigruzki.rkn.gov.ru/services/OperatorRequest/getLastDumpDate", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="lastDumpDate")]
        BlackList.ServiceReference.getLastDumpDateResponse getLastDumpDate(BlackList.ServiceReference.getLastDumpDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigruzki.rkn.gov.ru/services/OperatorRequest/getLastDumpDate", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackList.ServiceReference.getLastDumpDateResponse> getLastDumpDateAsync(BlackList.ServiceReference.getLastDumpDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigruzki.rkn.gov.ru/services/OperatorRequest/sendRequest", ReplyAction="*")]
        BlackList.ServiceReference.sendRequestResponse sendRequest(BlackList.ServiceReference.sendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigruzki.rkn.gov.ru/services/OperatorRequest/sendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackList.ServiceReference.sendRequestResponse> sendRequestAsync(BlackList.ServiceReference.sendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigruzki.rkn.gov.ru/services/OperatorRequest/getResult", ReplyAction="*")]
        BlackList.ServiceReference.getResultResponse getResult(BlackList.ServiceReference.getResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vigruzki.rkn.gov.ru/services/OperatorRequest/getResult", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackList.ServiceReference.getResultResponse> getResultAsync(BlackList.ServiceReference.getResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastDumpDate", WrapperNamespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", IsWrapped=true)]
    public partial class getLastDumpDateRequest {
        
        public getLastDumpDateRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastDumpDateResponse", WrapperNamespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", IsWrapped=true)]
    public partial class getLastDumpDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long lastDumpDate;
        
        public getLastDumpDateResponse() {
        }
        
        public getLastDumpDateResponse(long lastDumpDate) {
            this.lastDumpDate = lastDumpDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRequest", Namespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", Order=0)]
        public BlackList.ServiceReference.sendRequestRequestBody Body;
        
        public sendRequestRequest() {
        }
        
        public sendRequestRequest(BlackList.ServiceReference.sendRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] requestFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] signatureFile;
        
        public sendRequestRequestBody() {
        }
        
        public sendRequestRequestBody(byte[] requestFile, byte[] signatureFile) {
            this.requestFile = requestFile;
            this.signatureFile = signatureFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRequestResponse", Namespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", Order=0)]
        public BlackList.ServiceReference.sendRequestResponseBody Body;
        
        public sendRequestResponse() {
        }
        
        public sendRequestResponse(BlackList.ServiceReference.sendRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultComment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string code;
        
        public sendRequestResponseBody() {
        }
        
        public sendRequestResponseBody(bool result, string resultComment, string code) {
            this.result = result;
            this.resultComment = resultComment;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResult", Namespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", Order=0)]
        public BlackList.ServiceReference.getResultRequestBody Body;
        
        public getResultRequest() {
        }
        
        public getResultRequest(BlackList.ServiceReference.getResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public getResultRequestBody() {
        }
        
        public getResultRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResultResponse", Namespace="http://vigruzki.rkn.gov.ru/OperatorRequest/", Order=0)]
        public BlackList.ServiceReference.getResultResponseBody Body;
        
        public getResultResponse() {
        }
        
        public getResultResponse(BlackList.ServiceReference.getResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultComment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] registerZipArchive;
        
        public getResultResponseBody() {
        }
        
        public getResultResponseBody(bool result, string resultComment, byte[] registerZipArchive) {
            this.result = result;
            this.resultComment = resultComment;
            this.registerZipArchive = registerZipArchive;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperatorRequestPortTypeChannel : BlackList.ServiceReference.OperatorRequestPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperatorRequestPortTypeClient : System.ServiceModel.ClientBase<BlackList.ServiceReference.OperatorRequestPortType>, BlackList.ServiceReference.OperatorRequestPortType {
        
        public OperatorRequestPortTypeClient() {
        }
        
        public OperatorRequestPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperatorRequestPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorRequestPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorRequestPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlackList.ServiceReference.getLastDumpDateResponse BlackList.ServiceReference.OperatorRequestPortType.getLastDumpDate(BlackList.ServiceReference.getLastDumpDateRequest request) {
            return base.Channel.getLastDumpDate(request);
        }
        
        public long getLastDumpDate() {
            BlackList.ServiceReference.getLastDumpDateRequest inValue = new BlackList.ServiceReference.getLastDumpDateRequest();
            BlackList.ServiceReference.getLastDumpDateResponse retVal = ((BlackList.ServiceReference.OperatorRequestPortType)(this)).getLastDumpDate(inValue);
            return retVal.lastDumpDate;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackList.ServiceReference.getLastDumpDateResponse> BlackList.ServiceReference.OperatorRequestPortType.getLastDumpDateAsync(BlackList.ServiceReference.getLastDumpDateRequest request) {
            return base.Channel.getLastDumpDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackList.ServiceReference.getLastDumpDateResponse> getLastDumpDateAsync() {
            BlackList.ServiceReference.getLastDumpDateRequest inValue = new BlackList.ServiceReference.getLastDumpDateRequest();
            return ((BlackList.ServiceReference.OperatorRequestPortType)(this)).getLastDumpDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlackList.ServiceReference.sendRequestResponse BlackList.ServiceReference.OperatorRequestPortType.sendRequest(BlackList.ServiceReference.sendRequestRequest request) {
            return base.Channel.sendRequest(request);
        }
        
        public bool sendRequest(byte[] requestFile, byte[] signatureFile, out string resultComment, out string code) {
            BlackList.ServiceReference.sendRequestRequest inValue = new BlackList.ServiceReference.sendRequestRequest();
            inValue.Body = new BlackList.ServiceReference.sendRequestRequestBody();
            inValue.Body.requestFile = requestFile;
            inValue.Body.signatureFile = signatureFile;
            BlackList.ServiceReference.sendRequestResponse retVal = ((BlackList.ServiceReference.OperatorRequestPortType)(this)).sendRequest(inValue);
            resultComment = retVal.Body.resultComment;
            code = retVal.Body.code;
            return retVal.Body.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackList.ServiceReference.sendRequestResponse> BlackList.ServiceReference.OperatorRequestPortType.sendRequestAsync(BlackList.ServiceReference.sendRequestRequest request) {
            return base.Channel.sendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackList.ServiceReference.sendRequestResponse> sendRequestAsync(byte[] requestFile, byte[] signatureFile) {
            BlackList.ServiceReference.sendRequestRequest inValue = new BlackList.ServiceReference.sendRequestRequest();
            inValue.Body = new BlackList.ServiceReference.sendRequestRequestBody();
            inValue.Body.requestFile = requestFile;
            inValue.Body.signatureFile = signatureFile;
            return ((BlackList.ServiceReference.OperatorRequestPortType)(this)).sendRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlackList.ServiceReference.getResultResponse BlackList.ServiceReference.OperatorRequestPortType.getResult(BlackList.ServiceReference.getResultRequest request) {
            return base.Channel.getResult(request);
        }
        
        public bool getResult(string code, out string resultComment, out byte[] registerZipArchive) {
            BlackList.ServiceReference.getResultRequest inValue = new BlackList.ServiceReference.getResultRequest();
            inValue.Body = new BlackList.ServiceReference.getResultRequestBody();
            inValue.Body.code = code;
            BlackList.ServiceReference.getResultResponse retVal = ((BlackList.ServiceReference.OperatorRequestPortType)(this)).getResult(inValue);
            resultComment = retVal.Body.resultComment;
            registerZipArchive = retVal.Body.registerZipArchive;
            return retVal.Body.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackList.ServiceReference.getResultResponse> BlackList.ServiceReference.OperatorRequestPortType.getResultAsync(BlackList.ServiceReference.getResultRequest request) {
            return base.Channel.getResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackList.ServiceReference.getResultResponse> getResultAsync(string code) {
            BlackList.ServiceReference.getResultRequest inValue = new BlackList.ServiceReference.getResultRequest();
            inValue.Body = new BlackList.ServiceReference.getResultRequestBody();
            inValue.Body.code = code;
            return ((BlackList.ServiceReference.OperatorRequestPortType)(this)).getResultAsync(inValue);
        }
    }
}
